# Generated by Django 3.2.3 on 2021-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210520_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
