# Generated by Django 3.2.3 on 2021-05-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_link',
        ),
    ]
